language: python
python:
- '3.6'
cache: pip
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
- pip install -r requirements.txt
# Install Chrome Web Driver
- wget -N https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
- python process_html.py
- python web_driver.py
- python build_test.py