language: python
python:
- '3.6'
cache: 
- pip
addons:
- chrome: stable
services:
- xvfb

install:
- pip install -r src/requirements.txt
# Install Chrome Web Driver
- wget -N https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
- python src/process_html.py
- python src/web_driver.py
- python src/build_test.py